version: "3"
services: # containers
  redis-server:
    image: "redis"
  node-app:
    restart: always
    build: .
    ports:
      - "8081:8081"
# docker compose is used for starting multiple containers at the same time
# very easy to write all the configuration that are passed to Docker-CLI for the containers
